import Head from 'next/head'
import Image from 'next/image'

import Search from '@/components/Search'
import Header from '@/components/Header'

export default function Home () {
  return (
    <>
      <Head>
        <title>Google</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <Header />

      <div className='flex flex-col items-center mt-24'>
        <Image
          src='/logo.webp'
          alt='Logo google'
          width={300}
          height={100}
        />

        <Search />
      </div>
    </>
  )
}
